from app.models import Comment, db, environment, SCHEMA
from sqlalchemy.sql import text

def comment_seed_data(all_users, all_pins):
     comment1 = Comment(comment='Poster grids provide structure while allowing for creative freedom.', user_id=1, pin_id=1)
     comment2 = Comment(comment='Posters embrace diverse styles to resonate with varied audiences.', user_id=1, pin_id=1)
     comment3 = Comment(comment='Creative expression flourishes in the world of poster design.', user_id=1, pin_id=1)
     comment4 = Comment(comment='Effective posters communicate messages instantly and memorably.', user_id=1, pin_id=2)
     comment5 = Comment(comment='Whitespace strategically directs attention in minimalist posters.', user_id=1, pin_id=2)
     comment6 = Comment(comment='Poster design adapts to diverse cultural and demographic nuances.', user_id=1, pin_id=2)
     comment7 = Comment(comment='Visual consistency across a campaign strengthens brand identity.', user_id=1, pin_id=3)
     comment8 = Comment(comment='Poster layouts balance text and visuals for maximum impact.', user_id=1, pin_id=3)
     comment9 = Comment(comment='Color psychology influences emotional responses in posters.', user_id=1, pin_id=3)
     comment10 = Comment(comment='Typography hierarchy guides the flow of information in posters.', user_id=1, pin_id=4)
     comment11 = Comment(comment='Posters merge artistry and strategy for memorable communication.', user_id=1, pin_id=4)
     comment12 = Comment(comment='Design principles guide the creation of impactful poster campaigns.', user_id=1, pin_id=4)
     comment13 = Comment(comment='Poster layouts adapt to various print and digital platforms.', user_id=1, pin_id=5)
     comment14 = Comment(comment='Interactive elements in posters encourage audience engagement.', user_id=1, pin_id=5)
     comment15 = Comment(comment='Posters celebrate cultural diversity through visual expressions.', user_id=1, pin_id=5)
     comment16 = Comment(comment='Typography legibility ensures effective communication in posters.', user_id=1, pin_id=6)
     comment17 = Comment(comment='Poster color palettes evoke specific emotions and responses.', user_id=1, pin_id=6)
     comment18 = Comment(comment='Poster design navigates the delicate balance of form and function.', user_id=1, pin_id=6)
     comment19 = Comment(comment='Graphic elements in posters convey messages beyond words.', user_id=1, pin_id=7)
     comment20 = Comment(comment='Posters engage viewers with bold and captivating visuals.', user_id=1, pin_id=7)
     comment21 = Comment(comment='Poster grids establish visual order and harmony in design layouts.', user_id=1, pin_id=7)
     comment22 = Comment(comment='Creative typography treatments elevate poster messaging.', user_id=1, pin_id=8)
     comment23 = Comment(comment='Poster color psychology influences audience perceptions and responses.', user_id=1, pin_id=8)
     comment24 = Comment(comment='Collage techniques in posters blend diverse elements for artistic expression.', user_id=1, pin_id=8)
     comment25 = Comment(comment='Poster design embraces minimalism for impactful and memorable visuals.', user_id=1, pin_id=9)
     comment26 = Comment(comment='Interactive QR codes in posters bridge physical and digital experiences.', user_id=1, pin_id=9)
     comment27 = Comment(comment='Posters as visual storytelling platforms convey narratives succinctly.', user_id=1, pin_id=9)
     comment28 = Comment(comment='Typography hierarchy guides viewer engagement in poster layouts.', user_id=1, pin_id=10)
     comment29 = Comment(comment='Poster design trends reflect societal values and concerns.', user_id=1, pin_id=10)
     comment30 = Comment(comment='Poster design challenges conventions for avant-garde visual statements.', user_id=1, pin_id=10)


     comment31 = Comment(comment='Gradient mesh in Illustrator achieves realistic shading and depth.', user_id=2, pin_id=11)
     comment32 = Comment(comment='Pattern brushes in Illustrator apply intricate textures effortlessly.', user_id=2, pin_id=11)
     comment33 = Comment(comment='Efficient workflows in Illustrator save time and resources.', user_id=2, pin_id=11)
     comment34 = Comment(comment="Illustrator's gradients enhance dimensionality in design.", user_id=2, pin_id=12)
     comment35 = Comment(comment='Typography in Illustrator benefits from extensive font libraries.', user_id=2, pin_id=12)
     comment36 = Comment(comment="Illustrator's path adjustments refine complex vector shapes.", user_id=2, pin_id=12)
     comment37 = Comment(comment="Precision in Illustrator aligns elements for a polished look.", user_id=2, pin_id=13)
     comment38 = Comment(comment="Artboards in Illustrator organize and streamline design projects.", user_id=2, pin_id=13)
     comment39 = Comment(comment="Customizable patterns in Illustrator enhance design versatility.", user_id=2, pin_id=13)
     comment40 = Comment(comment="Illustrator's blend tool creates seamless color transitions.", user_id=2, pin_id=14)
     comment41 = Comment(comment='Vector graphics in Illustrator maintain crispness at any scale.', user_id=2, pin_id=14)
     comment42 = Comment(comment="Illustrator's global colors ensure efficient design updates.", user_id=2, pin_id=14)
     comment43 = Comment(comment="Illustrator transforms concepts into visually stunning realities.", user_id=2, pin_id=15)
     comment44 = Comment(comment="Illustrator's 3D effects bring depth to vector graphics.", user_id=2, pin_id=15)
     comment45 = Comment(comment="Illustrator's Pathfinder tool unleashes creative shape possibilities.", user_id=2, pin_id=15)
     comment46 = Comment(comment="Illustrator's gradient tools craft smooth color transitions.", user_id=2, pin_id=16)
     comment47 = Comment(comment="Artistic freedom flourishes with Illustrator's custom brushes.", user_id=2, pin_id=16)
     comment48 = Comment(comment='Pixel preview in Illustrator ensures design accuracy.', user_id=2, pin_id=16)
     comment49 = Comment(comment='Pattern creation in Illustrator adds depth to design elements.', user_id=2, pin_id=17)
     comment50 = Comment(comment='Clipping masks create visually compelling Illustrator effects.', user_id=2, pin_id=17)
     comment51 = Comment(comment="Illustrator's artboard features streamline workflow.", user_id=2, pin_id=17)
     comment52 = Comment(comment='Creative typography finds a home in Illustrator projects.', user_id=2, pin_id=18)
     comment53 = Comment(comment='Symbol libraries expedite repetitive tasks in Illustrator.', user_id=2, pin_id=18)
     comment54 = Comment(comment="Illustrator's global colors ensure design consistency.", user_id=2, pin_id=18)
     comment55 = Comment(comment='Bezier curves empower artists in Adobe Illustrator.', user_id=2, pin_id=19)
     comment56 = Comment(comment="Illustrator's blend tool seamlessly merges shapes.", user_id=2, pin_id=19)
     comment57 = Comment(comment='Layers organize complexity in Illustrator projects.', user_id=2, pin_id=19)
     comment58 = Comment(comment='Gradient meshes bring realism to Illustrator designs.', user_id=2, pin_id=20)
     comment59 = Comment(comment='Pen tool mastery is key to precise Illustrator artwork.', user_id=2, pin_id=20)
     comment60 = Comment(comment='Adobe Illustrator simplifies intricate vector illustrations.', user_id=2, pin_id=20)


     comment61 = Comment(comment='Photography captures fleeting moments, preserving memories.', user_id=3, pin_id=21)
     comment62 = Comment(comment='Filters in photography evoke specific moods and atmospheres.', user_id=3, pin_id=21)
     comment63 = Comment(comment='Photography composition emphasizes the beauty of simplicity.', user_id=3, pin_id=21)
     comment64 = Comment(comment='Photography storytelling transcends language barriers', user_id=3, pin_id=22)
     comment65 = Comment(comment='Creative angles and perspectives redefine photographic narratives.', user_id=3, pin_id=22)
     comment66 = Comment(comment='Photography editing enhances colors, tones, and visual impact.', user_id=3, pin_id=22)
     comment67 = Comment(comment='Nature photography celebrates the beauty of the natural world.', user_id=3, pin_id=23)
     comment68 = Comment(comment='Portrait photography immortalizes individual personalities.', user_id=3, pin_id=23)
     comment69 = Comment(comment='Photography lighting techniques create captivating visual drama.', user_id=3, pin_id=23)
     comment70 = Comment(comment='Photography reflects cultural diversity, fostering understanding.', user_id=3, pin_id=24)
     comment71 = Comment(comment='Photography perspectives shape the emotional impact of visual stories.', user_id=3, pin_id=24)
     comment72 = Comment(comment='Photography reflections add depth and complexity to visual narratives.', user_id=3, pin_id=24)
     comment73 = Comment(comment='Photography lighting experiments push creative boundaries for unique effects.', user_id=3, pin_id=25)
     comment74 = Comment(comment='Photography as an art form challenges societal norms and perceptions.', user_id=3, pin_id=25)
     comment75 = Comment(comment='Long exposure photography captures the passage of time and movement.', user_id=3, pin_id=25)
     comment76 = Comment(comment='Photography post-processing techniques evoke specific historical eras.', user_id=3, pin_id=26)
     comment77 = Comment(comment='Digital filters in photography software create diverse visual atmospheres.', user_id=3, pin_id=26)
     comment78 = Comment(comment='Photography storytelling transcends language barriers for global resonance.', user_id=3, pin_id=26)
     comment79 = Comment(comment='Photography composition principles enhance the visual appeal of images.', user_id=3, pin_id=27)
     comment80 = Comment(comment='Photography as a form of self-expression captures individual perspectives.', user_id=3, pin_id=27)
     comment81 = Comment(comment='Photography empowers individuals to share unique perspectives.', user_id=3, pin_id=27)
     comment82 = Comment(comment='Photography storytelling transcends genres and niches.', user_id=3, pin_id=28)
     comment83 = Comment(comment="Photography perspectives challenge viewers' perceptions.", user_id=3, pin_id=28)
     comment84 = Comment(comment='Macro photography explores the intricate details of subjects.', user_id=3, pin_id=28)
     comment85 = Comment(comment='Photography lighting techniques evoke specific moods and atmospheres.', user_id=3, pin_id=29)
     comment86 = Comment(comment='Candid photography captures authentic and spontaneous moments.', user_id=3, pin_id=29)
     comment87 = Comment(comment='Photography editing software enhances post-production creativity.', user_id=3, pin_id=29)
     comment88 = Comment(comment='Photography composition adheres to the rule of thirds for balance.', user_id=3, pin_id=30)
     comment89 = Comment(comment='Black and white photography conveys timeless elegance and drama.', user_id=3, pin_id=30)
     comment90 = Comment(comment='Photography captures the essence of fleeting emotions.', user_id=3, pin_id=30)


     comment91 = Comment(comment='Graphic design resonates through simplicity and clarity.', user_id=4, pin_id=31)
     comment92 = Comment(comment='Icons and symbols communicate universally in graphic design.', user_id=4, pin_id=31)
     comment93 = Comment(comment='Visual hierarchy guides viewer attention in graphic layouts.', user_id=4, pin_id=31)
     comment94 = Comment(comment='Consistent branding elements unify diverse graphic materials.', user_id=4, pin_id=32)
     comment95 = Comment(comment='Graphic design fosters emotional connections through visuals.', user_id=4, pin_id=32)
     comment96 = Comment(comment='Storyboards in graphic design outline visual narratives.', user_id=4, pin_id=32)
     comment97 = Comment(comment='Graphic design evolves with the integration of new technologies.', user_id=4, pin_id=33)
     comment98 = Comment(comment='Contrast in graphic design emphasizes key visual elements.', user_id=4, pin_id=33)
     comment99 = Comment(comment='Dynamic layouts elevate graphic design compositions.', user_id=4, pin_id=33)
     comment100 = Comment(comment='Typography choices shape the voice of graphic design projects.', user_id=4, pin_id=34)
     comment101 = Comment(comment='Texture enriches the tactile experience in graphic design.', user_id=4, pin_id=34)
     comment102 = Comment(comment='Graphic design embraces innovation for timeless appeal.', user_id=4, pin_id=34)
     comment103 = Comment(comment='Responsive design adapts seamlessly across various platforms.', user_id=4, pin_id=35)
     comment104 = Comment(comment='Dynamic shapes add energy to graphic design compositions.', user_id=4, pin_id=35)
     comment105 = Comment(comment='Visual consistency builds trust in graphic design projects.', user_id=4, pin_id=35)
     comment106 = Comment(comment='Graphic design blends creativity with strategic communication.', user_id=4, pin_id=36)
     comment107 = Comment(comment="Whitespace isn't empty; it's a powerful design element.", user_id=4, pin_id=36)
     comment108 = Comment(comment='Color theory guides impactful decision-making in design.', user_id=4, pin_id=36)
     comment109 = Comment(comment='Infographics simplify complex information for easy understanding.', user_id=4, pin_id=37)
     comment110 = Comment(comment='Graphic designers weave narratives through visual storytelling.', user_id=4, pin_id=37)
     comment111 = Comment(comment='Branding relies on consistent graphic design elements.', user_id=4, pin_id=37)
     comment112 = Comment(comment='Graphic design conveys emotion through imagery and color.', user_id=4, pin_id=38)
     comment113 = Comment(comment='Whitespace breathes life into graphic design compositions.', user_id=4, pin_id=38)
     comment114 = Comment(comment='Visual hierarchy guides viewer attention in design.', user_id=4, pin_id=38)
     comment115 = Comment(comment='Vector graphics ensure scalability and sharpness.', user_id=4, pin_id=39)
     comment116 = Comment(comment='Contrast adds depth and intrigue to graphic elements.', user_id=4, pin_id=39)
     comment117 = Comment(comment='Balance and symmetry create harmony in graphic layouts.', user_id=4, pin_id=39)
     comment118 = Comment(comment='Minimalism speaks volumes in modern graphic design.', user_id=4, pin_id=40)
     comment119 = Comment(comment='Typography choices define the essence of graphic compositions.', user_id=4, pin_id=40)
     comment120 = Comment(comment='Vibrant colors enhance visual impact in graphic design.', user_id=4, pin_id=40)


     all_comments =[comment1, comment2, comment3, comment4, comment5, comment6, comment7, comment8, comment9, comment10, comment11, comment12, comment13, comment14, comment15, comment16, comment17, comment18, comment19, comment20, comment21, comment22, comment23, comment24, comment25, comment26, comment27, comment28, comment29, comment30, comment31, comment32, comment33, comment34, comment35, comment36, comment37, comment38, comment39, comment40, comment41, comment42, comment43, comment44, comment45, comment46, comment47, comment48, comment49, comment50, comment51, comment52, comment53, comment54, comment55, comment56, comment57, comment58, comment59, comment60, comment61, comment62, comment63, comment64, comment65, comment66, comment67, comment68, comment69, comment70, comment71, comment72, comment73, comment74, comment75, comment76, comment77, comment78, comment79, comment80, comment81, comment82, comment83, comment84, comment85, comment86, comment87, comment88, comment89, comment90, comment91, comment92, comment93, comment94, comment95, comment96, comment97, comment98, comment99, comment100, comment101, comment102, comment103, comment104, comment105, comment106, comment107, comment108, comment109, comment110, comment111, comment112, comment113, comment114, comment115, comment116, comment117, comment118, comment119, comment120
     ]

     db.session.add_all(all_comments)
     db.session.commit()
     return all_comments

def undo_comment_seeds():
     if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.comments RESTART IDENTITY CASCADE;")
     else:
        db.session.execute(text("DELETE FROM comments"))
     db.session.commit()
